name: main
on:
  push:
    branches:
      - githubActions_improvement
jobs:
  syntax_check_job:
    name: Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: LinterExecution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: githubActions_improvement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  test_execution_job:
    name : Test execution
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm install jest
             npm run test
  #     - name: Setting node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - name: LinterExecution
  #       uses: github/super-linter@v3
  #       env:
  #         DEFAULT_BRANCH: nodejs_nodeversions_job
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
  #         VALIDATE_JAVASCRIPT_ES: true
  # test-execution:
  #   name: test-execution
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run jest tests
  #       run: npm install jest
  #             npm run test