name: main
on:
  push:
    branches:
      - githubActions_improvement
jobs:
  syntax_check_job:
    name: Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: LinterExecution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: githubActions_improvement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  test_execution_job:
    name: Test execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run test
        run: | 
            npm i
            npm run test
  build_statics_job:
    name: Build
    runs-on: ubuntu-latest
    needs: [syntax_check_job, test_execution_job] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          npm i
          npm run buildDev
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_statics_job] 
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy Artifacts
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: javisolercanto.surge.sh
          project: .
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}